using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Tareas.Models;

namespace Tareas.Controllers
{
    public class Tarea2Controller: Controller
    {
        private List<Elemento> list = new List<Elemento>
        {
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
            new Elemento{},
        };


        public IActionResult Index()
        {
            ViewData["Route"] = new List<HomeButtonsRequest>{
                new HomeButtonsRequest{Text="Home", ActionName = "Home"},
                new HomeButtonsRequest{Text="Tarea 2", ActionName = "Tarea2"}
            };
            return View(this.list);
        }
    }
}