using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Tareas.Models;
using Microsoft.AspNetCore.Authorization;

namespace Tareas.Controllers
{
    [AllowAnonymous]
    public class Tarea2Controller: Controller
    {
        private List<Elemento> list = new List<Elemento>
        {
new Elemento{Simbolo="H",   Nombre="Hidrógeno",     Grupo=	1	, Periodo=	1, Tipo=SubTipo.OtrosNoMetales	},
new Elemento{Simbolo="He",  Nombre="Helio	",      Grupo=	18	, Periodo=	1, Tipo=SubTipo.GasesNobles	},
new Elemento{Simbolo="Li",  Nombre="Litio	",      Grupo=	1	, Periodo=	2, Tipo=SubTipo.Alcalinos	},
new Elemento{Simbolo="Be",  Nombre="Berilio	",      Grupo=	2	, Periodo=	2, Tipo=SubTipo.Alcalinos_Terreos	},
new Elemento{Simbolo="B",   Nombre="Boro	",      Grupo=	13	, Periodo=	2, Tipo=SubTipo.Metaloides	},
new Elemento{Simbolo="C",   Nombre="Carbono	",      Grupo=	14	, Periodo=	2, Tipo=SubTipo.OtrosNoMetales	},
new Elemento{Simbolo="N",   Nombre="Nitrógeno",     Grupo=	15	, Periodo=	2, Tipo=SubTipo.OtrosNoMetales	},
new Elemento{Simbolo="O",   Nombre="Oxígeno	",      Grupo=	16	, Periodo=	2, Tipo=SubTipo.OtrosNoMetales	},
new Elemento{Simbolo="F",   Nombre="Flúor	",      Grupo=	17	, Periodo=	2, Tipo=SubTipo.Halogenos	},
new Elemento{Simbolo="Ne",  Nombre="Neón	",      Grupo=	18	, Periodo=	2, Tipo=SubTipo.GasesNobles	},
new Elemento{Simbolo="Na",  Nombre="Sodio	",      Grupo=	1	, Periodo=	3, Tipo=SubTipo.Alcalinos	},
new Elemento{Simbolo="Mg",  Nombre="Magnesio",      Grupo=	2	, Periodo=	3, Tipo=SubTipo.Alcalinos_Terreos	},
new Elemento{Simbolo="Al",  Nombre="Aluminio",      Grupo=	13	, Periodo=	3, Tipo=SubTipo.OtrosMetales	},
new Elemento{Simbolo="Si",  Nombre="Silicio",       Grupo=	14	, Periodo=	3, Tipo=SubTipo.Metaloides	},
new Elemento{Simbolo="P",   Nombre="Fósforo",       Grupo=	15	, Periodo=	3, Tipo=SubTipo.OtrosNoMetales	},
new Elemento{Simbolo="S",   Nombre="Azufre	",      Grupo=	16	, Periodo=	3, Tipo=SubTipo.OtrosNoMetales	},
new Elemento{Simbolo="Cl",  Nombre="Cloro	",      Grupo=	17	, Periodo=	3, Tipo=SubTipo.Halogenos	},
new Elemento{Simbolo="Ar",  Nombre="Argón	",      Grupo=	18	, Periodo=	3, Tipo=SubTipo.GasesNobles	},
new Elemento{Simbolo="K",   Nombre="Potasio	",      Grupo=	1	, Periodo=	4, Tipo=SubTipo.Alcalinos	},
new Elemento{Simbolo="Ca",  Nombre="Calcio	",      Grupo=	2	, Periodo=	4, Tipo=SubTipo.Alcalinos_Terreos	},
new Elemento{Simbolo="Sc",  Nombre="Escandio	",  Grupo=	3	, Periodo=	4, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Ti",  Nombre="Titanio	",      Grupo=	4	, Periodo=	4, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="V",   Nombre="Vanadio	",      Grupo=	5	, Periodo=	4, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Cr",  Nombre="Cromo	",      Grupo=	6	, Periodo=	4, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Mn",  Nombre="Manganeso	",  Grupo=	7	, Periodo=	4, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Fe",  Nombre="Hierro	",      Grupo=	8	, Periodo=	4, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Co",  Nombre="Cobalto	",      Grupo=	9	, Periodo=	4, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Ni",  Nombre="Níquel	",      Grupo=	10	, Periodo=	4, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Cu",  Nombre="Cobre	",      Grupo=	11	, Periodo=	4, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Zn",  Nombre="Zinc	",      Grupo=	12	, Periodo=	4, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Ga",  Nombre="Galio	",      Grupo=	13	, Periodo=	4, Tipo=SubTipo.OtrosMetales	},
new Elemento{Simbolo="Ge",  Nombre="Germanio",      Grupo=	14	, Periodo=	4, Tipo=SubTipo.Metaloides	},
new Elemento{Simbolo="As",  Nombre="Arsénico",      Grupo=	15	, Periodo=	4, Tipo=SubTipo.Metaloides	},
new Elemento{Simbolo="Se",  Nombre="Selenio",       Grupo=	16	, Periodo=	4, Tipo=SubTipo.OtrosNoMetales	},
new Elemento{Simbolo="Br",  Nombre="Bromo",         Grupo=	17	, Periodo=	4, Tipo=SubTipo.Halogenos	},
new Elemento{Simbolo="Kr",  Nombre="Kriptón",       Grupo=	18	, Periodo=	4, Tipo=SubTipo.GasesNobles	},
new Elemento{Simbolo="Rb",  Nombre="Rubidio",       Grupo=	1	, Periodo=	5, Tipo=SubTipo.Alcalinos	},
new Elemento{Simbolo="Sr",  Nombre="Estroncio",     Grupo=	2	, Periodo=	5, Tipo=SubTipo.Alcalinos_Terreos	},
new Elemento{Simbolo="Y",   Nombre="Ytrio",         Grupo=	3	, Periodo=	5, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Zr",  Nombre="Zirconio",      Grupo=	4	, Periodo=	5, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Nb",  Nombre="Niobio",        Grupo=	5	, Periodo=	5, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Mo",  Nombre="Molibdeno",     Grupo=	6	, Periodo=	5, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Tc",  Nombre="Tecnecio",      Grupo=	7	, Periodo=	5, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Ru",  Nombre="Rutenio",       Grupo=	8	, Periodo=	5, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Rh",  Nombre="Rodio",         Grupo=	9	, Periodo=	5, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Pd",  Nombre="Paladio",       Grupo=	10	, Periodo=	5, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Ag",  Nombre="Plata",         Grupo=	11	, Periodo=	5, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Cd",  Nombre="Cadmio",        Grupo=	12	, Periodo=	5, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="In",  Nombre="Indio",         Grupo=	13	, Periodo=	5, Tipo=SubTipo.OtrosMetales	},
new Elemento{Simbolo="Sn",  Nombre="Estaño",        Grupo=	14	, Periodo=	5, Tipo=SubTipo.OtrosMetales	},
new Elemento{Simbolo="Sb",  Nombre="Antimonio",     Grupo=	15	, Periodo=	5, Tipo=SubTipo.Metaloides	},
new Elemento{Simbolo="Te",  Nombre="Teluro",        Grupo=	16	, Periodo=	5, Tipo=SubTipo.Metaloides	},
new Elemento{Simbolo="I",   Nombre="Yodo",          Grupo=	17	, Periodo=	5, Tipo=SubTipo.Halogenos	},
new Elemento{Simbolo="Xe",  Nombre="Xenón",         Grupo=	18	, Periodo=	5, Tipo=SubTipo.GasesNobles	},
new Elemento{Simbolo="Cs",  Nombre="Cesio",         Grupo=	1	, Periodo=	6, Tipo=SubTipo.Alcalinos	},
new Elemento{Simbolo="Ba",  Nombre="Bario",         Grupo=	2	, Periodo=	6, Tipo=SubTipo.Alcalinos_Terreos	},
new Elemento{Simbolo="La",  Nombre="Lantano",       Grupo=	3	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Ce",  Nombre="Cerio",         Grupo=	4	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Pr",  Nombre="Praseodimio",   Grupo=	5	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Nd",  Nombre="Neodimio",      Grupo=	6	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Pm",  Nombre="Prometio",      Grupo=	7	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Sm",  Nombre="Samario",       Grupo=	8	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Eu",  Nombre="Europio",       Grupo=	9	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Gd",  Nombre="Gadolinio",     Grupo=	10	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Tb",  Nombre="Terbio",        Grupo=	11	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Dy",  Nombre="Disprosio",     Grupo=	12	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Ho",  Nombre="Holmio",        Grupo=	13	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Er",  Nombre="Erbio",         Grupo=	14	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Tm",  Nombre="Tulio",         Grupo=	15	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Yb",  Nombre="Yterbio",       Grupo=	16	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Lu",  Nombre="Lutecio",       Grupo=	17	, Periodo=	9, Tipo=SubTipo.Lantinidos	},
new Elemento{Simbolo="Hf",  Nombre="Hafnio",        Grupo=	4	, Periodo=	6, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Ta",  Nombre="Tantalio",      Grupo=	5	, Periodo=	6, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="W",   Nombre="Wolframio",     Grupo=	6	, Periodo=	6, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Re",  Nombre="Renio",         Grupo=	7	, Periodo=	6, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Os",  Nombre="Osmio",         Grupo=	8	, Periodo=	6, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Ir",  Nombre="Iridio",        Grupo=	9	, Periodo=	6, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Pt",  Nombre="Platino",       Grupo=	10	, Periodo=	6, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Au",  Nombre="Oro",           Grupo=	11	, Periodo=	6, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Hg",  Nombre="Mercurio",      Grupo=	12	, Periodo=	6, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Tl",  Nombre="Talio",         Grupo=	13	, Periodo=	6, Tipo=SubTipo.OtrosMetales	},
new Elemento{Simbolo="Pb",  Nombre="Plomo",         Grupo=	14	, Periodo=	6, Tipo=SubTipo.OtrosMetales	},
new Elemento{Simbolo="Bi",  Nombre="Bismuto",       Grupo=	15	, Periodo=	6, Tipo=SubTipo.OtrosMetales	},
new Elemento{Simbolo="Po",  Nombre="Polonio",       Grupo=	16	, Periodo=	6, Tipo=SubTipo.Metaloides	},
new Elemento{Simbolo="At",  Nombre="Astato",        Grupo=	17	, Periodo=	6, Tipo=SubTipo.Halogenos	},
new Elemento{Simbolo="Rn",  Nombre="Radón",         Grupo=	18	, Periodo=	6, Tipo=SubTipo.GasesNobles	},
new Elemento{Simbolo="Fr",  Nombre="Francio",       Grupo=	1	, Periodo=	7, Tipo=SubTipo.Alcalinos	},
new Elemento{Simbolo="Ra",  Nombre="Radio",         Grupo=	2	, Periodo=	7, Tipo=SubTipo.Alcalinos_Terreos	},
new Elemento{Simbolo="Ac",  Nombre="Actinio",       Grupo=	3	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Th",  Nombre="Torio",         Grupo=	4	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Pa",  Nombre="Protactinio",   Grupo=	5	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="U",   Nombre="Uranio",        Grupo=	6	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Np",  Nombre="Neptunio",      Grupo=	7	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Pu",  Nombre="Plutonio",      Grupo=	8	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Am",  Nombre="Americio",      Grupo=	9	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Cm",  Nombre="Curio",         Grupo=	10	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Bk",  Nombre="Berkelio",      Grupo=	11	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Cf",  Nombre="Californio",    Grupo=	12	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Es",  Nombre="Einsteinio",    Grupo=	13	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Fm",  Nombre="Fermio",        Grupo=	14	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Md",  Nombre="Mendelevio",    Grupo=	15	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="No",  Nombre="Nobelio",       Grupo=	16	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Lr",  Nombre="Laurencio",     Grupo=	17	, Periodo=	10, Tipo=SubTipo.Actinidos	},
new Elemento{Simbolo="Rf",  Nombre="Rutherfordio",  Grupo=	4	, Periodo=	7, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Db",  Nombre="Dubnio",        Grupo=	5	, Periodo=	7, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Sg",  Nombre="Seaborgio",     Grupo=	6	, Periodo=	7, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Bh",  Nombre="Bohrio",        Grupo=	7	, Periodo=	7, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Hs",  Nombre="Hassio",        Grupo=	8	, Periodo=	7, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Mt",  Nombre="Meitnerio",     Grupo=	9	, Periodo=	7, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Ds",  Nombre="Darmstadtio",   Grupo=	10	, Periodo=	7, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Rg",  Nombre="Roentgenio",    Grupo=	11	, Periodo=	7, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Cn",  Nombre="Copernicio",    Grupo=	12	, Periodo=	7, Tipo=SubTipo.Metales_Transicion	},
new Elemento{Simbolo="Nh",  Nombre="Nihonio	",      Grupo=	13	, Periodo=	7, Tipo=SubTipo.OtrosMetales	},
new Elemento{Simbolo="Fl",  Nombre="Flerovio",      Grupo=	14	, Periodo=	7, Tipo=SubTipo.OtrosMetales	},
new Elemento{Simbolo="Mc",  Nombre="Moscovio",      Grupo=	15	, Periodo=	7, Tipo=SubTipo.OtrosMetales	},
new Elemento{Simbolo="Lv",  Nombre="Livermorio",    Grupo=	16	, Periodo=	7, Tipo=SubTipo.OtrosMetales	},
new Elemento{Simbolo="Ts",  Nombre="Teneso",        Grupo=	17	, Periodo=	7, Tipo=SubTipo.Halogenos	},
new Elemento{Simbolo="Og",  Nombre="Oganesón",      Grupo=	18	, Periodo=	7, Tipo=SubTipo.GasesNobles	},
new Elemento{Simbolo="La-Lu",Nombre="Lantinidos",    Grupo=3,      Periodo=  6, Tipo=SubTipo.Lantinidos },
new Elemento{Simbolo="Ac-Lr", Nombre="Actinisdos",  Grupo=3,      Periodo=  7, Tipo=SubTipo.Actinidos}
        };


        public IActionResult Index()
        {
            return View(this.list);
        }
    }
}